name: GitHub Actions Demo 
run-name: ${{ github.actor }} Ä‘ang thá»­ nghiá»‡m GitHub Actions ğŸš€ 
vÃ o lÃºc: [push] 
jobs: 
  Explore-GitHub-Actions: 
    runs-on: ubuntu-latest 
    steps: 
      - run: echo "ğŸ‰ CÃ´ng viá»‡c Ä‘Ã£ Ä‘Æ°á»£c tá»± Ä‘á»™ng kÃ­ch hoáº¡t bá»Ÿi sá»± kiá»‡n ${{ github.event_name }}." 
      - run: echo "ğŸ§ CÃ´ng viá»‡c nÃ y hiá»‡n Ä‘ang cháº¡y trÃªn mÃ¡y chá»§ ${{ runner.os }} do GitHub lÆ°u trá»¯!" 
      - run: echo "ğŸ” TÃªn nhÃ¡nh cá»§a báº¡n lÃ  ${{ github.ref }} vÃ  kho lÆ°u trá»¯ cá»§a báº¡n lÃ  ${{ github.repository }}." 
      - name: Kiá»ƒm tra mÃ£ kho lÆ°u trá»¯ 
        sá»­ dá»¥ng: actions/checkout@v4 
      - run: echo "ğŸ’¡ Kho lÆ°u trá»¯ ${{ github.repository }} Ä‘Ã£ Ä‘Æ°á»£c sao chÃ©p vÃ o runner." 
      - run: echo "ğŸ–¥ï¸ Quy trÃ¬nh lÃ m viá»‡c hiá»‡n Ä‘Ã£ sáºµn sÃ ng Ä‘á»ƒ kiá»ƒm tra mÃ£ cá»§a báº¡n trÃªn runner." 
      - name: Liá»‡t kÃª cÃ¡c tá»‡p trong kho lÆ°u trá»¯ 
        run: | 
          ls ${{ github.workspace }} 
      - run: echo "ğŸ Tráº¡ng thÃ¡i cá»§a cÃ´ng viá»‡c nÃ y lÃ  ${{ job.status }}."
